[build]
command = "ng build"
functions = "netlify/functions"
publish = "dist/currency-exchange/browser"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
